config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/nfl_arrests_api' => 'welcome#nfl_arrests_api'
  get '/query' => 'welcome#query'
  get '/by_team' => 'welcome#by_team'

end

app/models/arrests.rb
class Arrests < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index
 
  end

  def query
    injection = params[:q]
    
    if Rails.env.production?
      @arrests  = Arrests.where(" (team ilike '%#{injection}%' OR name ilike '%#{injection}%' OR pos ilike '%#{injection}%' OR arest_or_charge ilike '%#{injection}%' OR category ilike '%#{injection}%' OR description ilike '%#{injection}%'  OR outcome ilike '%#{injection}%')")
    else
      @arrests  = Arrests.where(" (team like '%#{injection}%' OR name like '%#{injection}%' OR pos like '%#{injection}%' OR arest_or_charge like '%#{injection}%' OR category like '%#{injection}%' OR description like '%#{injection}%'  OR outcome like '%#{injection}%')")
    end




    render json: {
        records: @arrests
    }


  end

  def nfl_arrests_api
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hbar-tmpls/_records.erb
<input type="text" class="typeahead"  placeholder="You can search by any attribute below. Results update as you type." >
<script id="some-template" type="text/x-handlebars-template">

  <table id="myTable" class="table table-striped"   >
    <thead>
     
      <th>date</th>
      <th>team</th>
      <th>name</th>
      <th>pos</th>
      <th>case</th>
      <th>category</th>
      <th>desc</th>
      <th>outcome</th>
      <th>Count <span class="results-count">{{records.length}}</span></th>
 
    </thead>
    <tbody>
      {{#records}}
        <tr>
          <td>{{date}}</td>
          <td>{{team}}</td>
          <td>{{name}}</td>
          <td>{{pos}}</td>
          <td>{{arest_or_charge}}</td>
          <td>{{category}}</td>
          <td>{{description}}</td>
          <td>{{outcome}}</td>
          <td> </td>
 
        </tr>
      {{/records}}
    </tbody>
  </table>
</script>
<div id="content-placeholder">&nbsp;</div>

app/views/layouts/_nav.erb
<div class="nav">
  <ul>
    <li><a href="/" class="<%= request.url ==  root_url ? "active-nav" : "d" %>">Search</a></li>
    <li> <%=link_to "Access the NFL Arrests API", nfl_arrests_api_path %></li>
    <li class="disclaimer"><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>  DISCLAIMER: WE ARE UNAFFILIATED. REPORTING ON PUBLIC INFO. DATA UPDATES DAILY @ 6PM (last update <%= Arrests.first.created_at %> ) <a href="http://www.usatoday.com/sports/nfl/arrests/" target="_blank">THANK YOU:   USA TODAY </a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arrest</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://tablesorter.com/__jquery.tablesorter.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="black-wrapper">
    <div class="container">
      <%= render "layouts/nav" %>
    </div> <!-- container -->
  </div>

 <%= yield %> 

 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55529909-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/welcome/_api_examples.erb
<pre class="table">
  <table class="table">
        <thead>
          <tr>
            <th>Route</th>
            <th>Action</th>
            <th>Params</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>/query</td>
            <td>GET</td>
            <td>q</td>
            <td class="notes">The q query param is short for query term. You can polymorphically search by team,
              <br> Name, Position, Case, Category, Description, and Outcome. See The search page for live examples.</td>
          </tr>

        </tbody>
  </table>

</pre>





<pre class="table">
  <h5>Example  response for New York Jets search <b>/query?q=NYJ</b></h5>
  "records": [
  {
  "id": 13,
  "date": "2014-09-04",
  "team": "NYJ",
  "name": "Quincy Enunwa",
  "pos": "WR",
  "arest_or_charge": "Arrested",
  "category": "Domestic violence",
  "description": "Charged with simple assault after alleged incident with woman at hotel in Florham Park, N.J.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 51,
  "date": "2013-12-30",
  "team": "NYJ",
  "name": "Kellen Winslow Jr.",
  "pos": "TE",
  "arest_or_charge": "Charged",
  "category": "Drugs",
  "description": "Accused of possession of synthetic marijuana after police responded to a complaint of him in a parked car outside a Target store in New Jersey on Nov. 19.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 68,
  "date": "2013-07-30",
  "team": "NYJ",
  "name": "Joe McKnight",
  "pos": "RB",
  "arest_or_charge": "Arrested",
  "category": "Outstanding warrant",
  "description": "Pulled over for speeding, he was accused of having outstanding warrants for previous unpaid traffic fines.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 81,
  "date": "2013-05-17",
  "team": "NYJ",
  "name": "Mike Goodson",
  "pos": "RB",
  "arest_or_charge": "Arrested",
  "category": "Drugs, gun",
  "description": "Accused of marijuana possession and having an illegal gun with hollow-point bullets.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 84,
  "date": "2013-04-29",
  "team": "NYJ",
  "name": "Claude Davis",
  "pos": "DE",
  "arest_or_charge": "Arrested",
  "category": "Drugs",
  "description": "Charged with marijuana possession after police saw occupied vehicle filled with smoke.",
  "outcome": "Resolution undetermined. Released by team day after arrest.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 85,
  "date": "2013-04-29",
  "team": "NYJ",
  "name": "Cliff Harris",
  "pos": "CB",
  "arest_or_charge": "Arrested",
  "category": "Drugs",
  "description": "Charged with marijuana possession after police saw occupied vehicle filled with smoke.",
  "outcome": "Resolution undetermined. Released by team.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 112,
  "date": "2012-10-31",
  "team": "NYJ",
  "name": "Bryan Thomas",
  "pos": "LB",
  "arest_or_charge": "Arrested",
  "category": "Domestic violence",
  "description": "Charged with assault on wife at their New Jersey home. He allegedly punched her in stomach.",
  "outcome": "Probation, pretrial intervention program.",
  "created_at": "2014-09-25T04:36:18.000Z",
  "updated_at": "2014-09-25T04:36:18.000Z"
  },
  {
  "id": 217,
  "date": "2010-09-21",
  "team": "NYJ",
  "name": "Braylon Edwards",
  "pos": "WR",
  "arest_or_charge": "Arrested",
  "category": "DUI",
  "description": "Pulled over at 5:15 a.m. because police say his windows were too tinted; smelled of alcohol and blood-alcohol measured .16",
  "outcome": "Pleaded guilty to misdemeanor. Deal included $500 fine, driver's license suspended for six months, entered into substance-abuse program.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 311,
  "date": "2008-11-29",
  "team": "NYJ",
  "name": "Shaun Ellis",
  "pos": "DE",
  "arest_or_charge": "Arrested",
  "category": "Drugs",
  "description": "Pulled over in Hanover, N.J., charged with marijuana possession, speeding and driving without insurance.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 408,
  "date": "2007-05-20",
  "team": "NYJ",
  "name": "Justin Miller",
  "pos": "CB",
  "arest_or_charge": "Arrested",
  "category": "Assault",
  "description": "Accused of third-degree assault after swinging at a man but hitting a woman instead at New York nightclub.",
  "outcome": "Resolution undetermined.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 443,
  "date": "2006-11-25",
  "team": "NYJ",
  "name": "Adrian Jones",
  "pos": "OT",
  "arest_or_charge": "Arrested",
  "category": "DUI",
  "description": "Pulled over for lane-change violation in New Jersey, he was was accused of drunken driving. Blood-alcohol content measured at .22.",
  "outcome": "Pleaded guilty to related charge. Driver's license suspended. Fined $20,000 by team.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 597,
  "date": "2003-10-01",
  "team": "NYJ",
  "name": "John Abraham",
  "pos": "DE",
  "arest_or_charge": "Arrested",
  "category": "DUI",
  "description": "Accused of refusing a sobriety test, drunk driving after crashing Hummer into fire hydrant in Baldwin, N.Y.",
  "outcome": "Pleaded guilty to reduced charge of driving while impaired, fined $330, benched by team for one game.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 643,
  "date": "2002-07-06",
  "team": "NYJ",
  "name": "Aaron Beasley",
  "pos": "CB",
  "arest_or_charge": "Charged",
  "category": "Battery",
  "description": "Accused of simple battery in bar fight in Jacksonville.",
  "outcome": "Dropped.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 675,
  "date": "2001-10-14",
  "team": "NYJ",
  "name": "Damien Robinson",
  "pos": "NYJ",
  "arest_or_charge": "Arrested",
  "category": "Gun",
  "description": "Pulled over outside Giants stadium, where bomb-sniffing dog helped lead police to an assault rifle in his trunk. He had permit for the gun in New York.",
  "outcome": "Charge dropped. Team fined him $30,000.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  },
  {
  "id": 738,
  "date": "2000-02-06",
  "team": "NYJ",
  "name": "Wayne Chrebet",
  "pos": "WR",
  "arest_or_charge": "Arrested",
  "category": "Disorderly conduct",
  "description": "Accused of disorderly conduct in altercation outside the Bamboo Bar in New Jersey.",
  "outcome": "Pleaded guilty to nuisance violation, fined $230.",
  "created_at": "2014-09-25T04:36:19.000Z",
  "updated_at": "2014-09-25T04:36:19.000Z"
  }
  ]
  }
</pre>

app/views/welcome/by_team.html.erb
 <%
    team_and_count = Arrests.all.map{|x| x.team}.inject(Hash.new(0)) { |total, e| total[e] += 1 ;total}.sort_by {|_key, value| value}.reverse

    doughnutData = []
    team_and_count.each_with_index do |x,i|
      _rand_color = i % 2 == 0 ? "#1C3667" : "#B52126"
      doughnutData << {
        value: x[1],
        color: _rand_color,
        highlight: "#EEE",
        label: x[0]
      }
    end
%>
 





<div class="container">
  <div id="canvas-holder">
    <canvas id="chart-area" width="150" height="150"/>
  </div>
</div>

  <script>
    var doughnutData = <%=  raw(doughnutData.to_json)     %>;
   

      window.onload = function(){
        var ctx = document.getElementById("chart-area").getContext("2d");
        window.myDoughnut = new Chart(ctx).Doughnut(doughnutData, {responsive : true});
      };
      



  </script>
  </body>
</html>

app/views/welcome/index.slim
.container
  = render 'hbar-tmpls/records'

= javascript_include_tag "init-app"

app/views/welcome/nfl_arrests_api.slim
.container
  h1 API DOCS
  p I plan on implementing more endpoints, and adding proper design to this site. I'd rec. <a href="https://github.com/sodigital/NFL-Arrests-API" target="_blank">forking the api and running it yourself</a>, as this is a free heroku vm, and most likely wont be in memory.

  = render "welcome/api_examples"